import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises } from '@vue/test-utils'
import { createLabelPrintingCoordinator, MAX_PRINT_QUEUE, MAX_PRINT_HISTORY } from '@/services/label.printing.coordinator.js'
let qz, api, channel, ownership, errors, sent, history, coordinator
const candidate = (scanCodeId = 8, template = 'KGT', revision = 'r1') => ({ scanJobId: 42, scanCodeId, parcelId: 7, template, revision })
const event = (...printCandidates) => ({ scanJobId: 42, userId: 9, printCandidates })
function deferred() { let resolve, reject; const promise = new Promise((a, b) => { resolve = a; reject = b }); return { promise, resolve, reject } }
beforeEach(async () => {
  qz = { state: { printer: 'TSC TE200' }, ready: vi.fn().mockResolvedValue(), submit: vi.fn().mockResolvedValue(), onDisconnect: vi.fn() }
  api = { label: vi.fn().mockResolvedValue({ revision: 'r1' }) }
  channel = { resume: vi.fn().mockResolvedValue(true), start: vi.fn().mockResolvedValue(), stop: vi.fn().mockResolvedValue() }
  ownership = { acquire: vi.fn().mockResolvedValue(true), release: vi.fn().mockResolvedValue() }
  errors = vi.fn(); sent = vi.fn(); history = new Set()
  coordinator = createLabelPrintingCoordinator({ qz, api, channel, ownership, onError: errors, onSent: sent, history })
  await coordinator.setScope(42, 9)
})
describe('serial label printing coordinator', () => {
  it('reports a missing printer once and discards all unsubmitted labels', async () => {
    await coordinator.arm('KGT')
    qz.ready.mockImplementationOnce(async () => { qz.state.printer = ''; throw new Error('printer disappeared') })
    coordinator.consume(event(candidate(1), candidate(2)))
    await flushPromises()
    expect(errors).toHaveBeenCalledTimes(1)
    expect(coordinator.state).toMatchObject({ mode: 'Off', queued: 0, failed: null, paused: false })
    qz.state.printer = 'Office'
    coordinator.consume(event(candidate(3)))
    expect(qz.submit).not.toHaveBeenCalled()
  })
  it('propagates manual and retry printer failures after turning automatic marking off', async () => {
    await coordinator.arm('TJ')
    qz.ready.mockImplementationOnce(async () => { qz.state.printer = ''; throw new Error('manual printer missing') })
    await expect(coordinator.manual(candidate())).rejects.toThrow('manual printer missing')
    expect(coordinator.state.mode).toBe('Off')
    expect(errors).not.toHaveBeenCalled()
    qz.state.printer = 'Office'
    await coordinator.arm('KGT')
    coordinator.pause(new Error('connection lost'))
    qz.ready.mockImplementationOnce(async () => { qz.state.printer = ''; throw new Error('retry printer missing') })
    await expect(coordinator.retry()).rejects.toThrow('retry printer missing')
    expect(coordinator.state).toMatchObject({ mode: 'Off', paused: false })
    expect(errors).toHaveBeenCalledTimes(1)
  })
  it('reports missing-printer cleanup failure technically without replacing the original failure', async () => {
    await coordinator.arm('KGT')
    const report = vi.spyOn(console, 'error').mockImplementation(() => {})
    channel.stop.mockRejectedValueOnce(new Error('cleanup failed'))
    qz.ready.mockImplementationOnce(async () => { qz.state.printer = ''; throw new Error('missing printer') })
    coordinator.consume(event(candidate()))
    await flushPromises()
    expect(errors).toHaveBeenCalledExactlyOnceWith(expect.objectContaining({ message: 'missing printer' }))
    expect(report).toHaveBeenCalledWith('[missing printer cleanup]', expect.objectContaining({ message: 'cleanup failed' }))
    report.mockRestore()
  })
  it('honors Core KGT/TJ candidates, ignores ineligible scopes and deduplicates rescans by scan/revision', async () => {
    coordinator.consume(event(candidate()))
    expect(api.label).not.toHaveBeenCalled()
    await coordinator.arm('KGT')
    coordinator.consume({ ...event(candidate()), userId: 10 })
    coordinator.consume({ ...event(candidate()), scanJobId: 41 })
    coordinator.consume(event({ ...candidate(), scanJobId: 41 }, candidate(8, 'TJ_EXPORT')))
    coordinator.consume({ scanJobId: 42, userId: 9 })
    coordinator.consume(event(candidate(9), candidate(8), candidate(9)))
    await flushPromises()
    expect(api.label.mock.calls.map(([target]) => target.scanCodeId)).toEqual([9, 8])
    coordinator.consume(event(candidate(8)))
    coordinator.consume(event(candidate(10)))
    await flushPromises()
    expect(api.label).toHaveBeenCalledTimes(3)
    expect(coordinator.state.last.scanCodeId).toBe(10)
    await coordinator.arm('TJ')
    coordinator.consume(event(candidate(11, 'KGT'), candidate(12, 'TJ_EXPORT')))
    await flushPromises()
    expect(api.label).toHaveBeenLastCalledWith(candidate(12, 'TJ_EXPORT'))
    await coordinator.arm('Off')
    expect(coordinator.state.mode).toBe('Off')
  })
  it('serializes bursts during navigation without replaying snapshots or reconnect duplicates', async () => {
    await coordinator.arm('KGT')
    const first = deferred()
    qz.submit.mockReturnValueOnce(first.promise)
    coordinator.consume(event(candidate(1)))
    await flushPromises()
    coordinator.consume(event(candidate(2), candidate(3)))
    expect(qz.submit).toHaveBeenCalledTimes(1)
    expect(coordinator.state.queued).toBe(2)
    first.resolve()
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(3)
    // A reconnect reuses the same ledger and never reconstructs work from rows.
    await coordinator.arm('KGT')
    coordinator.consume(event(candidate(1), candidate(2), candidate(3), candidate(4)))
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(4)
    api.label.mockResolvedValueOnce({ revision: 'r2' })
    coordinator.consume(event(candidate(4, 'KGT', 'r2')))
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(5)
  })
  it('fetches fresh labels for manual repeat, captures identity and coalesces clicks', async () => {
    const wait = deferred()
    api.label.mockReturnValueOnce(wait.promise)
    const target = { scanJobId: 42, parcelId: 7, template: 'WBRN' }
    const pending = coordinator.manual(target)
    target.parcelId = 99
    expect(await coordinator.manual(target)).toBe(false)
    await flushPromises()
    expect(api.label).toHaveBeenCalledWith({ scanJobId: 42, parcelId: 7, template: 'WBRN' })
    wait.resolve({ revision: 'r1' })
    expect(await pending).toBe(true)
    await coordinator.manual(candidate())
    await coordinator.manual(candidate())
    expect(api.label).toHaveBeenCalledTimes(3)
    expect(history.size).toBe(0)
  })
  it('does not overlap automatic and manual submissions', async () => {
    await coordinator.arm('KGT')
    const wait = deferred()
    qz.submit.mockReturnValueOnce(wait.promise)
    const manual = coordinator.manual(candidate(1))
    await flushPromises()
    coordinator.consume(event(candidate(2)))
    expect(qz.submit).toHaveBeenCalledTimes(1)
    expect(await coordinator.manual(candidate(3))).toBe(false)
    wait.resolve()
    await manual
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(2)
  })
  it('pauses on ambiguous submission, reports once and retries only explicitly', async () => {
    await coordinator.arm('KGT')
    qz.submit.mockRejectedValueOnce(new Error('ambiguous'))
    coordinator.consume(event(candidate(1), candidate(2)))
    await flushPromises()
    expect(coordinator.state.failed.scanCodeId).toBe(1)
    expect(coordinator.state.paused).toBe(true)
    expect(errors).toHaveBeenCalledTimes(1)
    coordinator.consume(event(candidate(1)))
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(1)
    expect(await coordinator.manual(candidate(5))).toBe(false)
    qz.ready.mockRejectedValueOnce(new Error('still offline'))
    await expect(coordinator.retry()).rejects.toThrow('still offline')
    expect(coordinator.state.failed.scanCodeId).toBe(1)
    await coordinator.retry()
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(3)
    expect(coordinator.state.failed).toBeNull()
    expect(coordinator.state.paused).toBe(false)
  })
  it('reports a QZ disconnect and its failed pending submission only once', async () => {
    await coordinator.arm('KGT')
    const pending = deferred()
    qz.submit.mockReturnValueOnce(pending.promise)
    coordinator.consume(event(candidate(1)))
    await flushPromises()
    qz.onDisconnect.mock.calls[0][0](new Error('QZ stopped'))
    pending.reject(new Error('print connection lost'))
    await flushPromises()
    expect(errors).toHaveBeenCalledTimes(1)
    expect(coordinator.state.failed.scanCodeId).toBe(1)
  })
  it('surfaces server rendering failures and revision mismatch without sending', async () => {
    await coordinator.arm('KGT')
    coordinator.consume(event({ ...candidate(), errorCode: 'Overflow', revision: null }))
    await flushPromises()
    expect(errors).toHaveBeenCalledWith(expect.objectContaining({ code: 'Overflow' }))
    expect(api.label).not.toHaveBeenCalled()
    await coordinator.arm('KGT')
    api.label.mockResolvedValueOnce({ revision: 'r2' })
    coordinator.consume(event(candidate(9)))
    await flushPromises()
    expect(errors).toHaveBeenLastCalledWith(expect.objectContaining({ code: 'RevisionChanged' }))
    expect(qz.submit).not.toHaveBeenCalled()
  })
  it('bounds bursts and history with visible overflow/pause state', async () => {
    await coordinator.arm('KGT')
    coordinator.consume(event(...Array.from({ length: MAX_PRINT_QUEUE + 2 }, (_, i) => candidate(i))))
    expect(coordinator.state.overflow.scanCodeId).toBe(MAX_PRINT_QUEUE)
    expect(coordinator.state.queued).toBe(MAX_PRINT_QUEUE)
    expect(errors).toHaveBeenCalledTimes(1)
    expect(await coordinator.retry()).toBe(false)
    coordinator.consume(event(candidate(80)))
    expect(api.label).not.toHaveBeenCalled()
    await coordinator.disarm()
    for (let i = 0; i < MAX_PRINT_HISTORY; i++) history.add(`key${i}`)
    await coordinator.arm('KGT')
    coordinator.consume(event(candidate(100)))
    expect(coordinator.state.overflow.scanCodeId).toBe(100)
  })
  it('cancels unsubmitted fetches on job/operator changes, without canceling submitted jobs', async () => {
    const label = deferred()
    api.label.mockReturnValueOnce(label.promise)
    await coordinator.arm('KGT')
    coordinator.consume(event(candidate(1), candidate(2)))
    await flushPromises()
    await coordinator.setScope(43, 10)
    label.resolve({ revision: 'r1' })
    await flushPromises()
    expect(qz.submit).not.toHaveBeenCalled()
    expect(coordinator.state.queued).toBe(0)
    await coordinator.setScope(42, 9)
    await coordinator.arm('KGT')
    const submitted = deferred()
    qz.submit.mockReturnValueOnce(submitted.promise)
    coordinator.consume(event(candidate(3)))
    await flushPromises()
    await coordinator.disarm()
    submitted.resolve()
    await flushPromises()
    expect(qz.submit).toHaveBeenCalledTimes(1)
    expect(sent).not.toHaveBeenCalled()
  })
  it('cancels pending readiness, arm and retry, and ignores old failures after teardown', async () => {
    const ready = deferred()
    qz.ready.mockReturnValueOnce(ready.promise)
    const manual = coordinator.manual(candidate())
    await coordinator.disarm()
    ready.resolve()
    expect(await manual).toBe(false)
    const armReady = deferred()
    qz.ready.mockReturnValueOnce(armReady.promise)
    const arm = coordinator.arm('KGT')
    await flushPromises()
    await coordinator.disarm()
    armReady.reject(new Error('canceled'))
    await arm
    const lock = deferred()
    ownership.acquire.mockReturnValueOnce(lock.promise)
    const pendingLock = coordinator.arm('KGT')
    await flushPromises()
    await coordinator.disarm()
    lock.resolve(true)
    await pendingLock
    expect(coordinator.state.mode).toBe('Off')
    await coordinator.arm('KGT')
    const failed = deferred()
    api.label.mockReturnValueOnce(failed.promise)
    coordinator.consume(event(candidate(20)))
    await flushPromises()
    expect(await coordinator.retry()).toBe(false)
    await coordinator.disarm()
    failed.reject(new Error('old failure'))
    await flushPromises()
    expect(errors).not.toHaveBeenCalled()
    const retryReady = deferred()
    qz.ready.mockReturnValueOnce(retryReady.promise)
    const retry = coordinator.retry()
    await coordinator.disarm()
    retryReady.resolve()
    expect(await retry).toBe(false)
  })
  it('rejects arm and manual failures without publishing duplicates, and releases on failed stop', async () => {
    await coordinator.setScope(42, null)
    await expect(coordinator.arm('KGT')).rejects.toMatchObject({ code: 'NoOperator' })
    await coordinator.setScope(42, 9)
    await expect(coordinator.arm('bad')).rejects.toMatchObject({ code: 'InvalidData' })
    qz.ready.mockRejectedValueOnce(new Error('unavailable'))
    await expect(coordinator.arm('KGT')).rejects.toThrow('unavailable')
    ownership.acquire.mockResolvedValueOnce(false)
    await expect(coordinator.arm('TJ')).rejects.toMatchObject({ code: 'OtherTab' })
    channel.start.mockRejectedValueOnce(new Error('server unavailable'))
    await expect(coordinator.arm('KGT')).rejects.toThrow('server unavailable')
    api.label.mockRejectedValueOnce(new Error('invalid label'))
    await expect(coordinator.manual(candidate())).rejects.toThrow('invalid label')
    expect(errors).not.toHaveBeenCalled()
    await coordinator.arm('KGT')
    qz.onDisconnect.mock.calls[0][0](new Error('QZ stopped'))
    qz.onDisconnect.mock.calls[0][0](new Error('again'))
    expect(errors).toHaveBeenCalledTimes(1)
    await coordinator.retry()
    channel.stop.mockRejectedValueOnce(new Error('stop'))
    await expect(coordinator.disarm()).rejects.toThrow('stop')
    expect(ownership.release).toHaveBeenCalled()
    coordinator.pause(new Error('ignored'))
    expect(errors).toHaveBeenCalledTimes(1)
  })
})
