import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { computed, defineComponent, reactive, ref } from 'vue'
import { createPinia } from 'pinia'
import { flushPromises, mount } from '@vue/test-utils'
import LocalLabelPrinting from '@/components/LocalLabelPrinting.vue'
import MonitorLabelActions from '@/components/MonitorLabelActions.vue'
import PrinterConfigurationDialog from '@/l2/PrinterConfigurationDialog.vue'
import PageAlertRegion from '@/components/PageAlertRegion.vue'
import ScanjobMonitorSummary from '@/components/ScanjobMonitorSummary.vue'
import { useAlertStore } from '@/stores/alert.store.js'
import { LABEL_PRINTING_KEY } from '@/helpers/label.printing.helpers.js'
import { automaticPrintHistory } from '@/services/label.printing.coordinator.js'
import { roleAdmin, roleWhManager, roleWhOperator } from '@/helpers/user.roles.js'
const env = vi.hoisted(() => ({}))
vi.mock('@/stores/auth.store.js', () => ({ useAuthStore: () => env.auth }))
vi.mock('@/composables/useAppConfirm.js', () => ({ useAppConfirm: () => env.confirm }))
vi.mock('@/services/qz.printing.js', async (original) => ({ ...await original(), createQzPrinting: () => env.qz }))
vi.mock('@/services/printing.ownership.js', () => ({ createPrintingOwnership: () => env.ownership }))
vi.mock('@/services/printing.api.js', () => ({ printingApi: { label: (...args) => env.label(...args) }, createPrintChannel: (event, error) => { env.event = event; env.failure = error; return env.channel } }))

const stubs = {
  'font-awesome-icon': { props: ['icon'], template: '<i :data-icon="icon" />' },
  'v-tooltip': { inheritAttrs: false, template: '<div><slot name="activator" :props="{}" /></div>' },
  'v-btn': { props: ['disabled', 'loading'], template: '<button :disabled="disabled || loading"><slot /></button>' },
  'v-select': { props: ['modelValue', 'items', 'disabled', 'label'], emits: ['update:modelValue'], template: '<label>{{ label }}<select :value="modelValue" :disabled="disabled" @change="$emit(\'update:modelValue\', $event.target.value)"><option value=""></option><option v-for="item in items" :key="item.value || item" :value="item.value || item" :disabled="item.props?.disabled">{{ item.title || item }}</option></select></label>' },
  'v-dialog': { props: ['modelValue'], template: '<div v-if="modelValue" role="dialog"><slot /></div>' },
  'v-card': { template: '<div><slot /></div>' }, 'v-card-title': { template: '<div><slot /></div>' }, 'v-card-text': { template: '<div><slot /></div>' }, 'v-card-actions': { template: '<div><slot /></div>' }
}
const host = defineComponent({ components: { LocalLabelPrinting, PageAlertRegion, ScanjobMonitorSummary }, template: '<div><hr class="hr" /><PageAlertRegion v-if="!printing?.configurationOpen" /><LocalLabelPrinting ref="printing" :scan-job-id="job" :user-id="user" :active="active" /><ScanjobMonitorSummary :print-queue="printing?.queueStatus" /></div>', setup: () => ({ printing: ref(null), job: ref(42), user: ref(9), active: ref(true) }) })
let wrapper, alerts, errorSpy
beforeEach(() => {
  automaticPrintHistory.clear()
  env.auth = reactive({ user: { token: 'token' } })
  env.confirm = vi.fn().mockResolvedValue(true)
  env.label = vi.fn().mockResolvedValue({ revision: 'r1', language: 'TSPL' })
  env.channel = { resume: vi.fn().mockResolvedValue(true), start: vi.fn().mockResolvedValue(), stop: vi.fn().mockResolvedValue() }
  env.ownership = { acquire: vi.fn().mockResolvedValue(true), release: vi.fn().mockResolvedValue() }
  const state = reactive({ printer: 'TSC TE200', printers: ['Office', 'TSC TE200'], connected: true })
  env.qz = { state, connect: vi.fn().mockResolvedValue(state.printers), ready: vi.fn().mockResolvedValue(), select: vi.fn((name) => { state.printer = name }), clearSelection: vi.fn(() => { state.printer = '' }), submit: vi.fn().mockResolvedValue(), disconnect: vi.fn().mockResolvedValue(), onDisconnect: vi.fn() }
  const pinia = createPinia()
  alerts = useAlertStore(pinia)
  errorSpy = vi.spyOn(alerts, 'error')
  wrapper = mount(host, { global: { plugins: [pinia], stubs } })
})
afterEach(async () => { if (wrapper) wrapper.unmount(); await flushPromises(); vi.restoreAllMocks() })
const panel = () => wrapper.getComponent(LocalLabelPrinting)
const target = { parcelId: 7, template: 'WBRN' }
const scan = (id = 8) => ({ scanJobId: 42, userId: 9, printCandidates: [{ scanJobId: 42, scanCodeId: id, parcelId: 7, template: 'KGT', revision: 'r1' }] })
async function openSettings() {
  if (!panel().find('[data-testid="print-settings-dialog"]').exists()) {
    await panel().get('[data-testid="print-settings-action"]').trigger('click')
    await flushPromises()
  }
}
async function arm() { await openSettings(); await panel().get('[data-testid="auto-print-mode"] select').setValue('KGT'); await flushPromises() }
describe('local printing UI', () => {
  it.each([roleAdmin, roleWhManager, roleWhOperator].flatMap((role) =>
    ['KGT', 'TJ'].map((mode) => ({ role, mode }))
  ))('prints $mode scans from a different scanner account for $role', async ({ role, mode }) => {
    env.auth.user = { id: 100, roles: [role], token: 'ui-user-token' }
    await openSettings()
    const selector = panel().get('[data-testid="auto-print-mode"] select')
    expect(selector.get(`option[value="${mode}"]`).element.disabled).toBe(false)
    await selector.setValue(mode)
    await flushPromises()
    expect(env.channel.start).toHaveBeenCalledExactlyOnceWith(42, 9)
    const template = mode === 'KGT' ? 'KGT' : 'TJ_EXPORT'
    const event = { ...scan(), printCandidates: [{ ...scan().printCandidates[0], template }] }
    env.event({ ...event, userId: 100 })
    await flushPromises()
    expect(env.label).not.toHaveBeenCalled()
    env.event(event)
    await flushPromises()
    expect(env.label).toHaveBeenCalledExactlyOnceWith(event.printCandidates[0])
    expect(env.qz.submit).toHaveBeenCalledOnce()
    expect(panel().get('[data-testid="print-settings-action"]').classes()).toContain('anti-btn-green')
    expect(wrapper.get('[data-testid="page-alert-region"] [role="status"]').text()).toContain('Этикетка отправлена в очередь принтера')
    expect(errorSpy).not.toHaveBeenCalled()
  })

  it.each([roleAdmin, roleWhManager, roleWhOperator])(
    'presents a different operator label failure once and retries it for %s', async (role) => {
      env.auth.user = { id: 100, roles: [role], token: 'ui-user-token' }
      await arm()
      env.label.mockRejectedValueOnce(new Error('label unavailable'))
      env.event(scan())
      await flushPromises()
      expect(wrapper.findAll('[role="alert"]')).toHaveLength(1)
      expect(wrapper.get('[role="alert"]').text()).toContain('label unavailable')
      expect(errorSpy).toHaveBeenCalledOnce()
      expect(env.qz.submit).not.toHaveBeenCalled()
      expect(wrapper.vm.job).toBe(42)
      expect(wrapper.vm.user).toBe(9)
      expect(panel().vm.queueStatus.paused).toBe(true)
      await panel().get('[data-testid="retry-print"]').trigger('click')
      await flushPromises()
      expect(env.label).toHaveBeenNthCalledWith(2, scan().printCandidates[0])
      expect(env.qz.submit).toHaveBeenCalledOnce()
      expect(wrapper.get('[data-testid="page-alert-region"] [role="status"]').text()).toContain('Этикетка отправлена в очередь принтера')
      expect(panel().vm.queueStatus.paused).toBe(false)
      expect(errorSpy).toHaveBeenCalledOnce()
    }
  )

  it('keeps one visible alert region and retains errors when closing configuration', async () => {
    env.qz.connect.mockRejectedValueOnce(new Error('printer list failed'))
    await openSettings()
    expect(wrapper.findAllComponents(PageAlertRegion)).toHaveLength(1)
    expect(wrapper.get('[role="dialog"]').get('[role="alert"]').text()).toContain('printer list failed')
    await panel().get('[data-testid="close-print-settings"]').trigger('click'); await flushPromises()
    expect(wrapper.findAllComponents(PageAlertRegion)).toHaveLength(1)
    const alert = wrapper.get('[data-testid="page-alert-region"]')
    expect(alert.text()).toContain('printer list failed')
    expect(alert.element.previousElementSibling.tagName).toBe('HR')
    expect(errorSpy).toHaveBeenCalledOnce()
  })
  it('selects printers directly, sorts TE200 first and renders the translated marking modes', async () => {
    env.qz.state.printers = ['Office Z', 'TSC TE200', 'Office A']
    expect(panel().get('[data-testid="print-settings-action"] [data-icon]').attributes('data-icon')).toBe('fa-solid fa-print')
    expect(panel().get('[data-testid="print-settings-action"]').classes()).not.toContain('anti-btn-green')
    await openSettings()
    expect(env.qz.connect).toHaveBeenCalledOnce()
    expect(panel().get('[data-testid="printer-selection-inline"] select').findAll('option').map((item) => item.text())).toEqual(['', 'TSC TE200', 'Office A', 'Office Z'])
    expect(panel().get('[data-testid="auto-print-mode"] select').findAll('option').map((item) => item.text())).toEqual(['', 'Отключён', 'Таджикистан', 'КГТ'])
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office A')
    expect(env.qz.select).toHaveBeenCalledWith('Office A')
    expect(wrapper.findAll('[role="dialog"]')).toHaveLength(1)
    expect(panel().vm.operationInProgress).toBe(false)
    await panel().get('[data-testid="auto-print-mode"] select').setValue('TJ')
    await flushPromises()
    expect(env.channel.start).toHaveBeenCalledWith(42, 9)
    expect(panel().vm.operationInProgress).toBe(false)
    expect(panel().get('[data-testid="print-settings-action"]').classes()).toContain('anti-btn-green')
    await panel().get('[data-testid="auto-print-mode"] select').setValue('Off')
    await flushPromises()
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(panel().get('[data-testid="print-settings-action"]').classes()).not.toContain('anti-btn-green')
  })
  it('clears selection, disables enabled modes and keeps marking off after selecting a printer', async () => {
    await arm()
    env.qz.submit.mockRejectedValueOnce(new Error('paused print'))
    env.event({ ...scan(), printCandidates: [...scan().printCandidates, ...scan(9).printCandidates] })
    await flushPromises()
    expect(wrapper.get('[data-testid="scanjob-monitor-print-queue"]').text()).toContain('1 — приостановлена')
    expect(panel().vm.operationInProgress).toBe(false)
    await panel().get('[data-testid="clear-printer"]').trigger('click')
    await flushPromises()
    expect(env.qz.clearSelection).toHaveBeenCalledOnce()
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(wrapper.get('[data-testid="scanjob-monitor-print-queue"]').text()).toContain('0')
    const enabledModes = panel().get('[data-testid="auto-print-mode"] select').findAll('option').slice(2)
    expect(enabledModes.every((option) => option.element.disabled)).toBe(true)
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office')
    await flushPromises()
    env.event(scan(10)); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(1)
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
  })
  it('presents list refresh and inline selection failures once and permits retry', async () => {
    env.qz.connect.mockRejectedValueOnce(new Error('list unavailable'))
    await openSettings()
    expect(wrapper.get('[role="alert"]').text()).toContain('list unavailable')
    expect(errorSpy).toHaveBeenCalledTimes(1)
    await panel().get('[data-testid="refresh-printers"]').trigger('click'); await flushPromises()
    expect(env.qz.connect).toHaveBeenCalledTimes(2)
    await arm()
    expect(panel().get('[data-testid="printer-selection-inline"] select').element.disabled).toBe(false)
    env.qz.select.mockImplementationOnce(() => { throw new Error('selection denied') })
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('selection denied')
    expect(env.qz.state.printer).toBe('TSC TE200')
    expect(errorSpy).toHaveBeenCalledTimes(2)
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office'); await flushPromises()
    expect(env.qz.state.printer).toBe('Office')
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('KGT')
    expect(env.channel.start).toHaveBeenCalledOnce()
  })
  it('presents lock acquisition rejection once and retries the same marking mode', async () => {
    env.ownership.acquire.mockRejectedValueOnce(new Error('lock request failed'))
    await arm()
    expect(wrapper.get('[role="dialog"]').get('[role="alert"]').text()).toContain('lock request failed')
    expect(wrapper.findAll('[role="alert"]')).toHaveLength(1)
    expect(errorSpy).toHaveBeenCalledOnce()
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(env.qz.state.printer).toBe('TSC TE200')
    expect(env.channel.start).not.toHaveBeenCalled()
    expect(panel().vm.operationInProgress).toBe(false)
    await arm()
    expect(env.ownership.acquire).toHaveBeenCalledTimes(2)
    expect(env.channel.start).toHaveBeenCalledExactlyOnceWith(42, 9)
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('KGT')
    expect(errorSpy).toHaveBeenCalledOnce()
  })
  it('exposes live operation and queue state while printing, with no queue count in the header', async () => {
    let finish
    await arm()
    env.qz.submit.mockReturnValueOnce(new Promise((resolve) => { finish = resolve }))
    env.event({ ...scan(), printCandidates: [...scan().printCandidates, ...scan(9).printCandidates] })
    await flushPromises()
    expect(panel().vm.operationInProgress).toBe(true)
    expect(panel().vm.queueStatus).toEqual({ queued: 1, paused: false })
    expect(wrapper.get('[data-testid="scanjob-monitor-print-queue"]').text()).toContain('1')
    expect(panel().text()).not.toContain('В очереди')
    finish(); await flushPromises()
    expect(panel().vm.operationInProgress).toBe(false)
    expect(panel().vm.queueStatus.queued).toBe(0)
  })
  it('reports failed stopping while clearing, preserves selection and retries clear', async () => {
    await openSettings()
    env.channel.stop.mockRejectedValueOnce(new Error('cannot stop'))
    await panel().get('[data-testid="clear-printer"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('cannot stop')
    expect(errorSpy).toHaveBeenCalledOnce()
    expect(env.qz.clearSelection).not.toHaveBeenCalled()
    expect(env.qz.state.printer).toBe('TSC TE200')
    await panel().get('[data-testid="clear-printer"]').trigger('click'); await flushPromises()
    expect(env.qz.state.printer).toBe('')
  })
  it('shows refresh progress and turns off marking if a refreshed printer list loses its selection', async () => {
    let fail
    await arm()
    env.qz.connect.mockReturnValueOnce(new Promise((resolve, reject) => { fail = reject }))
    await panel().get('[data-testid="close-print-settings"]').trigger('click'); await flushPromises()
    await panel().get('[data-testid="print-settings-action"]').trigger('click'); await flushPromises()
    expect(panel().vm.operationInProgress).toBe(true)
    env.qz.state.printer = ''
    fail({ code: 'PrinterMissing' }); await flushPromises()
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(errorSpy).toHaveBeenCalledExactlyOnceWith(expect.stringContaining('отсутствует'))
    expect(panel().vm.operationInProgress).toBe(false)
  })
  it('shows queued success, fetches fresh on repeat and presents manual rejection exactly once', async () => {
    await panel().vm.printParcel(target)
    expect(env.label).toHaveBeenCalledWith({ ...target, scanJobId: 42 })
    expect(wrapper.get('[data-testid="page-alert-region"]').text()).toContain('Физическая печать не подтверждена')
    env.label.mockRejectedValueOnce({ data: { code: 'Overflow' } })
    await panel().vm.printParcel(target)
    expect(errorSpy).toHaveBeenCalledTimes(1)
    expect(wrapper.get('[role="alert"]').text()).toContain('не помещается')
    expect(wrapper.vm.job).toBe(42)
    await panel().vm.printParcel(target)
    expect(env.label).toHaveBeenCalledTimes(3)
  })
  it('coalesces clicks and retains captured parcel/job through first-use selection', async () => {
    env.qz.state.printer = ''
    const captured = { ...target }
    await panel().vm.printParcel(captured)
    captured.parcelId = 99
    await panel().vm.printParcel(target)
    await flushPromises()
    expect(env.qz.connect).toHaveBeenCalledTimes(1)
    expect(wrapper.findAll('[role="dialog"]')).toHaveLength(1)
    expect(wrapper.get('[role="dialog"]').text()).toContain('Настройки печати')
    expect(wrapper.findAllComponents(PageAlertRegion)).toHaveLength(1)
    expect(panel().get('[data-testid="auto-print-mode"] select').element.disabled).toBe(true)
    await wrapper.get('[data-testid="print-pending-label"]').trigger('click')
    await flushPromises()
    expect(env.qz.select).toHaveBeenCalledWith('TSC TE200')
    expect(env.label).toHaveBeenCalledWith({ ...target, scanJobId: 42 })
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
  })
  it('preserves failed selection with visible failure and explicit cancel', async () => {
    env.qz.state.printer = ''
    env.qz.connect.mockRejectedValueOnce({ code: 'PrinterMissing' })
    await panel().vm.printParcel(target); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('отсутствует')
    const dialog = wrapper.getComponent(PrinterConfigurationDialog)
    await dialog.get('[data-testid="printer-selection-inline"] select').setValue('Office')
    expect(env.qz.select).not.toHaveBeenCalled()
    env.qz.select.mockImplementationOnce(() => { throw new Error('storage denied') })
    await wrapper.get('[data-testid="print-pending-label"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(true)
    expect(dialog.get('select').element.value).toBe('Office')
    expect(wrapper.get('[role="alert"]').text()).toContain('storage denied')
    expect(wrapper.findAll('[role="alert"]')).toHaveLength(1)
    await dialog.get('[data-testid="close-print-settings"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(errorSpy).toHaveBeenCalledTimes(2)
  })
  it('does not submit when selection is canceled or scope changes during selection', async () => {
    env.qz.state.printer = ''
    await panel().vm.printParcel(target)
    await flushPromises()
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office')
    await panel().get('[data-testid="close-print-settings"]').trigger('click'); await flushPromises()
    expect(env.label).not.toHaveBeenCalled()
    expect(env.qz.select).not.toHaveBeenCalled()
    await panel().vm.printParcel(target)
    wrapper.vm.job = 43; await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(env.label).not.toHaveBeenCalled()
  })
  it('keeps the captured pending print open through selection and printing failures, then retries it', async () => {
    env.qz.state.printer = ''
    const captured = { ...target }
    await panel().vm.printParcel(captured); await flushPromises()
    captured.parcelId = 99
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office')
    env.qz.select.mockImplementationOnce(() => { throw new Error('cannot save printer') })
    await panel().get('[data-testid="print-pending-label"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="dialog"]').get('[role="alert"]').text()).toContain('cannot save printer')
    expect(wrapper.findAll('[role="alert"]')).toHaveLength(1)
    expect(panel().get('[data-testid="printer-selection-inline"] select').element.value).toBe('Office')
    expect(env.label).not.toHaveBeenCalled()
    env.label.mockRejectedValueOnce(new Error('label unavailable'))
    await panel().get('[data-testid="print-pending-label"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="dialog"]').get('[role="alert"]').text()).toContain('label unavailable')
    expect(panel().get('[data-testid="printer-selection-inline"] select').element.value).toBe('Office')
    expect(wrapper.vm.job).toBe(42)
    expect(panel().vm.busy).toBe(true)
    expect(panel().vm.operationInProgress).toBe(false)
    await panel().vm.printParcel({ parcelId: 88, template: 'WBRN' })
    expect(env.label).toHaveBeenCalledTimes(1)
    await panel().get('[data-testid="print-pending-label"]').trigger('click'); await flushPromises()
    expect(env.label).toHaveBeenCalledTimes(2)
    expect(env.label).toHaveBeenNthCalledWith(1, { ...target, scanJobId: 42 })
    expect(env.label).toHaveBeenNthCalledWith(2, { ...target, scanJobId: 42 })
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(wrapper.findAllComponents(PageAlertRegion)).toHaveLength(1)
    expect(errorSpy).toHaveBeenCalledTimes(2)
    expect(panel().vm.busy).toBe(false)
  })
  it('suppresses repeated print confirmation and blocks cancellation while submission is pending', async () => {
    env.qz.state.printer = ''
    let finish
    env.qz.submit.mockReturnValueOnce(new Promise((resolve) => { finish = resolve }))
    await panel().vm.printParcel(target); await flushPromises()
    await panel().get('[data-testid="print-pending-label"]').trigger('click'); await flushPromises()
    expect(panel().vm.operationInProgress).toBe(true)
    expect(panel().get('[data-testid="close-print-settings"]').element.disabled).toBe(true)
    await wrapper.get('[role="dialog"]').trigger('keydown', { key: 'Escape' })
    expect(wrapper.find('[role="dialog"]').exists()).toBe(true)
    wrapper.getComponent(PrinterConfigurationDialog).vm.$emit('select', 'Office'); await flushPromises()
    expect(env.qz.select).toHaveBeenCalledTimes(1)
    expect(env.qz.submit).toHaveBeenCalledTimes(1)
    finish(); await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(panel().vm.operationInProgress).toBe(false)
  })
  it.each(['resolve', 'reject'])('discards a pending print when cancelled during discovery that later %ss', async (outcome) => {
    env.qz.state.printer = ''
    let finish, fail
    env.qz.connect.mockReturnValueOnce(new Promise((resolve, reject) => { finish = resolve; fail = reject }))
    await panel().vm.printParcel(target); await flushPromises()
    expect(panel().vm.operationInProgress).toBe(true)
    await panel().get('[data-testid="close-print-settings"]').trigger('click'); await flushPromises()
    if (outcome === 'resolve') finish(env.qz.state.printers)
    else fail(new Error('discovery failed'))
    await flushPromises()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(false)
    expect(panel().vm.operationInProgress).toBe(false)
    expect(env.label).not.toHaveBeenCalled()
    if (outcome === 'reject') {
      expect(wrapper.get('[role="alert"]').text()).toContain('discovery failed')
      expect(errorSpy).toHaveBeenCalledOnce()
    }
    await openSettings()
    expect(wrapper.getComponent(PrinterConfigurationDialog).props('pendingPrint')).toBe(false)
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office'); await flushPromises()
    expect(env.label).not.toHaveBeenCalled()
  })
  it('prints live candidates, pauses, confirms explicit retry, and permits manual last-label repeat', async () => {
    await arm()
    env.qz.submit.mockRejectedValueOnce({ code: 'SubmissionFailed' })
    env.event(scan())
    await flushPromises()
    expect(wrapper.get('[data-testid="failed-print"]').text()).toContain('скан 8')
    expect(wrapper.get('[role="alert"]').text()).toContain('дубликат')
    expect(errorSpy).toHaveBeenCalledTimes(1)
    env.confirm.mockResolvedValueOnce(false)
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(1)
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(2)
    await panel().get('[data-testid="reprint-label"]').trigger('click'); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(3)
    expect(env.label).toHaveBeenCalledTimes(3)
  })
  it('presents arm, retry and clear rejection once and retains monitor input', async () => {
    env.channel.start.mockRejectedValueOnce(new Error('follow failed'))
    await arm()
    expect(wrapper.get('[role="alert"]').text()).toContain('follow failed')
    expect(panel().get('[data-testid="print-settings-action"]').classes()).not.toContain('anti-btn-green')
    await arm()
    env.failure(new Error('connection lost')); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('connection lost')
    env.confirm.mockRejectedValueOnce(new Error('confirmation failed'))
    // A failed print needs confirmation; a connection-only pause resumes directly.
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    env.qz.submit.mockRejectedValueOnce(new Error('submission'))
    env.event(scan()); await flushPromises()
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('confirmation failed')
    env.qz.ready.mockRejectedValueOnce(new Error('retry unavailable'))
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('retry unavailable')
    env.qz.clearSelection.mockImplementationOnce(() => { throw new Error('clear failed') })
    await panel().get('[data-testid="clear-printer"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('clear failed')
    expect(wrapper.vm.user).toBe(9)
    expect(errorSpy).toHaveBeenCalledTimes(6)
  })
  it('turns off a missing printer, cancels its queue and requires explicitly arming again', async () => {
    await arm()
    env.qz.ready.mockImplementationOnce(async () => { env.qz.state.printer = ''; throw { code: 'PrinterMissing' } })
    env.event({ ...scan(), printCandidates: [...scan().printCandidates, ...scan(9).printCandidates] })
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('отсутствует')
    expect(errorSpy).toHaveBeenCalledTimes(1)
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(wrapper.get('[data-testid="scanjob-monitor-print-queue"]').text()).toContain('0')
    expect(wrapper.find('[data-testid="retry-print"]').exists()).toBe(false)
    await panel().get('[data-testid="printer-selection-inline"] select').setValue('Office'); await flushPromises()
    expect(env.qz.state.printer).toBe('Office')
    expect(env.qz.submit).not.toHaveBeenCalled()
    env.event(scan(10)); await flushPromises()
    expect(env.qz.submit).not.toHaveBeenCalled()
    await arm()
    env.event(scan(11)); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(1)
  })
  it('presents missing-printer storage failure once, turns off marking and permits refresh retry', async () => {
    await arm()
    env.qz.connect.mockImplementationOnce(async () => { env.qz.state.printer = ''; throw new Error('storage denied') })
    await panel().get('[data-testid="refresh-printers"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="dialog"]').get('[role="alert"]').text()).toContain('storage denied')
    expect(wrapper.findAll('[role="alert"]')).toHaveLength(1)
    expect(errorSpy).toHaveBeenCalledOnce()
    expect(panel().get('[data-testid="auto-print-mode"] select').element.value).toBe('Off')
    expect(panel().vm.operationInProgress).toBe(false)
    await panel().get('[data-testid="refresh-printers"]').trigger('click'); await flushPromises()
    expect(env.qz.connect).toHaveBeenCalledTimes(3)
    expect(errorSpy).toHaveBeenCalledOnce()
    expect(wrapper.find('[role="dialog"]').exists()).toBe(true)
    env.event(scan()); await flushPromises()
    expect(env.qz.submit).not.toHaveBeenCalled()
  })
  it('retains connection pause until scanner subscription is verified', async () => {
    await arm()
    env.failure(new Error('terminal closure')); await flushPromises()
    env.channel.resume.mockRejectedValueOnce(new Error('subscribe failed'))
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('subscribe failed')
    expect(panel().find('[data-testid="retry-print"]').exists()).toBe(true)
    await panel().get('[data-testid="retry-print"]').trigger('click'); await flushPromises()
    expect(panel().find('[data-testid="retry-print"]').exists()).toBe(false)
    env.event(scan()); await flushPromises()
    expect(env.qz.submit).toHaveBeenCalledTimes(1)
  })
  it('stops acceptance on logout, operator/job change, closed job and teardown', async () => {
    await arm()
    wrapper.vm.user = 10; await flushPromises()
    env.event(scan()); await flushPromises()
    expect(env.label).not.toHaveBeenCalled()
    wrapper.vm.user = 9; await flushPromises(); await arm()
    env.auth.user = null; await flushPromises()
    env.event(scan()); await flushPromises()
    expect(env.label).not.toHaveBeenCalled()
    wrapper.vm.active = false; await flushPromises()
    const report = vi.spyOn(console, 'error').mockImplementation(() => {})
    env.channel.stop.mockRejectedValueOnce(new Error('scope cleanup'))
    wrapper.vm.job = 43; await flushPromises()
    expect(report).toHaveBeenCalledWith('[local printing scope cleanup]', expect.any(Error))
    env.channel.stop.mockRejectedValueOnce(new Error('teardown failed'))
    wrapper.unmount(); wrapper = null; await flushPromises()
    expect(report).toHaveBeenCalledWith('[local printing teardown]', expect.any(Error))
    expect(env.qz.disconnect).toHaveBeenCalledOnce()
  })
  it.each([
    { stopFails: false, disconnectFails: false },
    { stopFails: true, disconnectFails: false },
    { stopFails: false, disconnectFails: true },
    { stopFails: true, disconnectFails: true }
  ])('attempts both unmount cleanup steps with stopFails=$stopFails and disconnectFails=$disconnectFails', async ({ stopFails, disconnectFails }) => {
    await arm()
    const report = vi.spyOn(console, 'error').mockImplementation(() => {})
    const stopError = new Error('channel stop failed'), disconnectError = new Error('QZ disconnect failed')
    if (stopFails) env.channel.stop.mockRejectedValueOnce(stopError)
    if (disconnectFails) env.qz.disconnect.mockRejectedValueOnce(disconnectError)
    env.channel.stop.mockClear()
    env.ownership.release.mockClear()
    wrapper.unmount(); wrapper = null; await flushPromises()
    expect(env.channel.stop).toHaveBeenCalledOnce()
    expect(env.ownership.release).toHaveBeenCalledOnce()
    expect(env.qz.disconnect).toHaveBeenCalledOnce()
    expect(report).toHaveBeenCalledTimes(Number(stopFails) + Number(disconnectFails))
    if (stopFails) expect(report).toHaveBeenCalledWith('[local printing teardown]', stopError)
    if (disconnectFails) expect(report).toHaveBeenCalledWith('[local printing disconnect]', disconnectError)
    expect(errorSpy).not.toHaveBeenCalled()
  })
  it('displays overflow pause', async () => {
    await arm()
    env.event({ ...scan(), printCandidates: Array.from({ length: 51 }, (_, i) => ({ ...scan().printCandidates[0], scanCodeId: i })) })
    await flushPromises()
    expect(wrapper.get('[data-testid="print-overflow"]').text()).toContain('скана 50')
    expect(wrapper.find('[data-testid="retry-print"]').exists()).toBe(false)
    expect(wrapper.get('[role="alert"]').text()).toContain('переполнена')
  })
})
describe('server-advertised monitor actions', () => {
  it('shows only manual capabilities, honors busy state and emits captured identity', async () => {
    const print = vi.fn(), busy = ref(false)
    const actions = mount(MonitorLabelActions, { props: { item: { id: 7, printableTemplates: ['WBRN', 'OZON', 'KGT'] } }, global: {
      provide: { [LABEL_PRINTING_KEY]: { print, busy: computed(() => busy.value) } },
      stubs: { ...stubs, 'v-tooltip': { inheritAttrs: false, template: '<div><slot name="activator" :props="{}" /><slot /></div>' } }
    } })
    expect(actions.findAll('button')).toHaveLength(2)
    expect(actions.findAll('button').map((button) => button.attributes('aria-label'))).toEqual([
      'Печать стикера Wildberries', 'Печать стикера Ozon'
    ])
    expect(actions.text()).toContain('Печать стикера Wildberries')
    expect(actions.text()).toContain('Печать стикера Ozon')
    await actions.findAll('button')[0].trigger('click')
    expect(print).toHaveBeenCalledWith({ parcelId: 7, template: 'WBRN' })
    await actions.findAll('button')[1].trigger('click')
    expect(print).toHaveBeenLastCalledWith({ parcelId: 7, template: 'OZON' })
    busy.value = true; await flushPromises()
    expect(actions.get('button').element.disabled).toBe(true)
    await actions.setProps({ item: { parcelId: 8 } })
    expect(actions.findAll('button')).toHaveLength(0)
    actions.unmount()
    const unprovided = mount(MonitorLabelActions, { props: { item: {} }, global: { stubs } })
    expect(unprovided.findAll('button')).toHaveLength(0)
    unprovided.unmount()
  })
})
