import { describe, expect, it, vi } from 'vitest'
import { flushPromises } from '@vue/test-utils'
import { createLabelPrintingCoordinator } from '@/services/label.printing.coordinator.js'
import { createQzPrinting } from '@/services/qz.printing.js'
import label from './fixtures/tajikistan-ruble-label.json'

// Fixture generated by core's TJ factory/renderer with a TJS unit price of 214,
// quantity 2, and the imported parcel total «Сумма в рублях» = 1234.50.
describe('TJ ruble total through web automatic printing and reprints', () => {
  it('delivers the corrected core TSPL unchanged to the raw printer for both actions', async () => {
    const bytes = Uint8Array.from(globalThis.atob(label.contentBase64), (character) => character.charCodeAt(0))
    const tspl = new globalThis.TextDecoder('windows-1251').decode(bytes)
    expect(tspl).toContain('1234,50 руб.')
    expect(tspl).not.toContain('428,00 руб.')
    expect(tspl).not.toContain('2469,00 руб.')
    expect(tspl).not.toContain('TEXT 16,212,')
    const client = {
      security: { setCertificatePromise: vi.fn(), setSignatureAlgorithm: vi.fn(), setSignaturePromise: vi.fn() },
      websocket: { isActive: () => true, setClosedCallbacks: vi.fn() },
      printers: { find: vi.fn().mockResolvedValue(['TSC TE200']) },
      configs: { create: vi.fn().mockReturnValue('config') }, print: vi.fn().mockResolvedValue()
    }
    const storage = { getItem: () => 'TSC TE200' }
    const qz = createQzPrinting({ client, api: {}, storage })
    const api = { label: vi.fn().mockResolvedValue(label) }
    const channel = { start: vi.fn().mockResolvedValue(), stop: vi.fn().mockResolvedValue() }
    const ownership = { acquire: vi.fn().mockResolvedValue(true), release: vi.fn().mockResolvedValue() }
    const onError = vi.fn()
    const coordinator = createLabelPrintingCoordinator({ qz, api, channel, ownership, onError, onSent: vi.fn(), history: new Set() })
    const candidate = { scanJobId: 42, scanCodeId: 8, parcelId: 7, template: 'TJ_EXPORT', revision: label.revision }
    await coordinator.setScope(42,9)
    await coordinator.arm('TJ')
    coordinator.consume({ scanJobId: 42, userId: 9, printCandidates: [candidate] })
    await flushPromises()
    expect(client.print).toHaveBeenCalledExactlyOnceWith('config', [{ type: 'raw', format: 'command', flavor: 'base64', data: label.contentBase64 }])
    expect(await coordinator.manual(candidate)).toBe(true)
    expect(api.label).toHaveBeenCalledTimes(2)
    expect(client.print).toHaveBeenCalledTimes(2)
    expect(client.print.mock.calls[1]).toEqual(client.print.mock.calls[0])
    expect(onError).not.toHaveBeenCalled()
    await coordinator.disarm()
  })
})
