export const ozonRegisterColumnTitles = {
  BoxNumber: 'Номер коробки',
  OzonId: 'ID отправления',
  PostingNumber: 'Номер отправления',
  ShipmentWeightKg: 'Вес отправления',
  PlacesCount: 'Кол-во мест',
  Barcode: 'Штрих код',
  Article: 'Артикул',
  Manufacturer: 'Производитель',
  Country: 'Страна',
  DescriptionEn: 'Описание на английском',
  ProductName: 'Описание на русском',
  WeightKg: 'Вес',
  Currency: 'Валюта',
  UnitPrice: 'Цена единицы',
  Quantity: 'Количество',
  ProductLink: 'Ссылка на страницу интернет-магазина',
  TnVed: 'Код ТНВЭД',
  LastName: 'Фамилия',
  FirstName: 'Имя',
  Patronymic: 'Отчество',
  Phone: 'Телефон',
  Email: 'Email',
  BirthDate: 'Дата рождения',
  PassportSeries: 'Серия паспорта',
  PassportNumber: 'Номер паспорта',
  PassportIssueDate: 'Дата выдачи паспорта',
  PassportIssuedBy: 'Кем выдан паспорт',
  Inn: 'ИНН',
  PostalCode: 'Индекс',
  City: 'Населенный пункт',
  Address: 'Адрес',
  Cmn: 'ЦМН',
  CmnId: 'ID ЦМН',
  Imei: 'IMEI',
  Imei2: 'IMEI 2',
  Comment: 'Комментарий',
  Status: 'Статус',
  CheckStatusId: 'Проверка'
}

export const ozonRegisterColumnTooltips = {
}
