export const registerColumnTitles = {
  RowNumber: 'п/п',
  OrderNumber: 'Номер заказа',
  InvoiceDate: 'Дата инвойса',
  Sticker: 'Стикер',
  Shk: 'ШК',
  StickerCode: 'Код стикера',
  ExtId: 'ext_id',
  TnVed: 'ТН ВЭД',
  SiteArticle: 'Артикул сайта',
  HeelHeight: 'Высота каблука (подошвы), см',
  Size: 'Размер',
  ProductName: 'Наименование товара',
  Description: 'Описание',
  Gender: 'Пол',
  Brand: 'Бренд',
  FabricType: 'Тип ткани (для обуви "ОБУВЬ", для одежды "трикотаж", "текстиль")',
  Composition: 'Состав (для обуви материал верха)',
  Lining: 'Подкладка',
  Insole: 'Стелька',
  Sole: 'Подошва',
  Country: 'страна',
  FactoryAddress: 'завод адрес',
  Unit: 'единица измерения (шт., пара)',
  WeightKg: 'Масса, кг,',
  Quantity: 'Кол-во',
  UnitPrice: 'Цена за 1 шт,',
  Currency: 'Валюта',
  Barcode: 'Баркод',
  Declaration: 'ГТД',
  ProductLink: 'Ссылка на товар',
  RecipientName: 'ФИО получателя физ. лица',
  RecipientInn: 'ИНН получателя физ. лица',
  PassportNumber: 'Номер паспорта',
  Pinfl: 'Пинфл',
  RecipientAddress: 'Адрес получателя физического лица',
  ContactPhone: 'Контактный номер',
  BoxNumber: 'Номер коробки',
  Supplier: 'Поставщик',
  SupplierInn: 'ИНН Поставщика',
  Category: 'Категория',
  Subcategory: 'Подкатегория',
  PersonalData: 'Персональные данные',
  CustomsClearance: 'Таможенное оформление',
  DutyPayment: 'Оплата пошлины',
  OtherReason: 'Другая причина'
}
