// Copyright (C) 2025 Maxim [maxirmx] Samsonov (www.sw.consulting)
// All rights reserved.
// This file is a part of Logibooks ui application 

export const wbrRegisterColumnTitles = {
  rowNumber: 'п/п',
  orderNumber: 'Номер посылки',
  invoiceDate: 'Дата инвойса',
  sticker: 'Стикер',
  shk: 'ШК',
  extId: 'ext_id',
  tnVed: 'ТН ВЭД',
  siteArticle: 'Артикул сайта',
  heelHeight: 'Высота каблука (подошвы), см',
  size: 'Размер',
  productName: 'Наименование товара',
  description: 'Описание',
  gender: 'Пол',
  brand: 'Бренд',
  fabricType: 'Тип ткани',
  composition: 'Состав',
  lining: 'Подкладка',
  insole: 'Стелька',
  sole: 'Подошва',
  countryCode: 'Страна',
  factoryAddress: 'Завод адрес',
  unit: 'Единица измерения',
  weightKg: 'Масса, кг',
  quantity: 'Кол-во',
  unitPrice: 'Цена за 1 шт',
  currency: 'Валюта',
  barcode: 'Баркод',
  declaration: 'ГТД',
  productLink: 'Ссылка на товар',
  recipientName: 'ФИО получателя физ. лица',
  recipientInn: 'ИНН получателя физ. лица',
  passportNumber: 'Номер паспорта',
  pinfl: 'Пинфл',
  recipientAddress: 'Адрес получателя физического лица',
  contactPhone: 'Контактный номер',
  boxNumber: 'Номер коробки',
  supplier: 'Поставщик',
  supplierInn: 'ИНН Поставщика',
  category: 'Категория',
  subcategory: 'Подкатегория',
  personalData: 'Персональные данные',
  customsClearance: 'Таможенное оформление',
  dutyPayment: 'Оплата пошлины',
  otherReason: 'Другая причина',
  statusId: 'Статус',
  checkStatus: 'Проверка'
}

export const wbrRegisterColumnTooltips = {
  fabricType: 'для обуви "ОБУВЬ", для одежды "трикотаж", "текстиль"',
  composition: 'для обуви материал верха',
  unit: 'шт., пара',
  weightKg: 'указывается в килограммах',
  unitPrice: 'цена за единицу товара',
  recipientName: 'полное имя физического лица получателя',
  recipientInn: 'индивидуальный номер налогоплательщика получателя',
  recipientAddress: 'полный адрес получателя для доставки',
  supplierInn: 'индивидуальный номер налогоплательщика поставщика'
}
