# Copyright (C) 2025 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Logibooks ui application 

name: publish

on:
  push:
    tags:     [ 'v*' ]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/logibooks.ui
          tags: |
            type=semver,pattern={{version}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ contains(github.ref, 'refs/tags/v') }}
            type=sha,enable=true
          labels: |
            org.opencontainers.image.vendor=sw.consulting
            org.opencontainers.image.title=Logibooks UI
            org.opencontainers.image.source==${{ github.repositoryUrl }}
            org.opencontainers.image.description=Logibooks UI container
          annotations: |
            org.opencontainers.image.licenses=BSD-2-Clause
            org.opencontainers.image.description=Logibooks UI container

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push:  ${{ contains(github.ref, 'refs/tags/v') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}